"""ADICIONE NO MODULO MOEDA.PY CRIADO NOS DESAFIOS ANTERIORES A FUNÇÃO CHAMADA RESUMO(), QUE MOSTRE NA TELA ALGUMAS INFORMAÇÕES GERADAS PELAS FUNÇÕES QUE JA TEMOS NO MODULO CRIADO ATE AQUI"""
import moeda

p = float(input('Digite um valor: '))
moeda.resumo(p, 80, 35)